spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8083


kafka:
  topic:
    name: activity-events
    cache-invalidation: cache-invalidation-events

cache:
  recommendation:
    ttl: 30m

logging:
  level:
    org.springframework.data.redis: INFO
    io.lettuce.core: INFO

gemini:
  api:
    key: ${GEMINI_KEY}
    url: ${GEMINI_URL}

